collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  config_default:
    path: config/_default
    name: Config Default
    icon: chair_alt
  config_development:
    path: config/development
    name: Config Development
    icon: mode_comment
  content_english:
    path: content/english
    name: Content English
    icon: contactless
  i18n:
    path: i18n
    name: I18n
    icon: iron
  data:
    path: data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
paths:
  static: static
  uploads: static/uploads
timezone: Europe/Stockholm
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
